<div class="row mt-3">
    <div class="col-12">
        <div class="card">
            <div class="card-header bg-primary text-white">
                <h6 class="mb-0">
                    <i class="bi bi-clipboard-plus me-2"></i>Instruksi PPA
                </h6>
            </div>
            <div class="card-body">
                <!-- Form Input untuk ADD Modal (ID yang benar) -->
                <div class="row g-3 mb-4">
                    <div class="col-md-4">
                        <label for="instruksi_ppa_search_input" class="form-label fw-bold">
                            <i class="bi bi-person-badge text-primary me-1"></i>Pilih PPA
                        </label>
                        <!-- Custom searchable dropdown untuk ADD -->
                        <div class="position-relative">
                            <input type="text" id="instruksi_ppa_search_input" class="form-control"
                                placeholder="Ketik nama ppa mencari..." autocomplete="off">
                            <input type="hidden" id="instruksi_ppa_selected_value" name="instruksi_ppa_perawat_select">

                            <!-- Dropdown list untuk ADD -->
                            <div id="edit_instruksi_ppa_dropdown" class="dropdown-menu w-100 shadow-lg"
                                style="display: none; max-height: 250px; overflow-y: auto; position: absolute; top: 100%; z-index: 1000;">
                                <!-- Items will be generated by JavaScript -->
                            </div>
                        </div>
                        <div class="form-text">
                            <i class="bi bi-search me-1"></i>Ketik untuk mencari nama PPA
                        </div>
                    </div>

                    <div class="col-md-6">
                        <label for="instruksi_ppa_text_input" class="form-label fw-bold">
                            <i class="bi bi-card-text text-primary me-1"></i>Instruksi
                        </label>
                        <textarea id="instruksi_ppa_text_input" class="form-control" rows="2"
                            placeholder="Masukkan instruksi untuk PPA yang dipilih..."></textarea>
                    </div>

                    <div class="col-md-2 d-flex align-items-end">
                        <button type="button" class="btn btn-primary w-100" id="instruksi_ppa_tambah_btn">
                            <i class="bi bi-plus-square me-1"></i>Tambah
                        </button>
                    </div>
                </div>

                <!-- Tabel List Instruksi untuk ADD Modal -->
                <div class="border rounded">
                    <div class="d-flex justify-content-between align-items-center p-3 bg-light border-bottom">
                        <h6 class="mb-0 fw-bold text-primary">
                            <i class="bi bi-list-check me-2"></i>List Instruksi PPA
                        </h6>
                        <span class="badge bg-secondary fs-6" id="instruksi_ppa_count_badge">0</span>
                    </div>

                    <div class="table-responsive">
                        <table class="table table-hover mb-0">
                            <thead class="table-light">
                                <tr>
                                    <th width="8%" class="text-center">No</th>
                                    <th width="30%">PPA</th>
                                    <th width="52%">Instruksi</th>
                                    <th width="10%" class="text-center">Aksi</th>
                                </tr>
                            </thead>
                            <tbody id="instruksi_ppa_table_body">
                                <tr>
                                    <td colspan="4" class="text-center text-muted py-5">
                                        <i class="bi bi-inbox display-4 d-block mb-3 opacity-50"></i>
                                        <span class="fs-6">Belum ada instruksi yang
                                            ditambahkan</span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <!-- Hidden inputs untuk ADD Modal -->
        <div id="instruksi_ppa_hidden_inputs"></div>
        <input type="hidden" id="instruksi_ppa_json_input" name="instruksi" value="">
    </div>
</div>
